IF
  Global("G#TF.TyrisMatch","GLOBAL",0)
  Global("G#TF.CheckTyrisMatch","GLOBAL",0)
  Gender(Player1,MALE)
  OR(3)
    Race(Player1,HUMAN)
    Race(Player1,HALF_ELF)
    Race(Player1,ELF)
THEN
  RESPONSE #1
    SetGlobal("G#TF.CheckTyrisMatch","GLOBAL",1)
    SetGlobal("G#TF.TyrisMatch","GLOBAL",1)
END

IF
  Global("G#TF.TyrisMatch","GLOBAL",0)
  Global("G#TF.CheckTyrisMatch","GLOBAL",0)
THEN
  RESPONSE #1
    SetGlobal("G#TF.CheckTyrisMatch","GLOBAL",1)
END
